config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[show]
      post 'users/sign_in', to: 'users#sign_in'

      resources :mangas, only: %i[show]
      resources :chapters, only: %i[show]
    end
  end

  devise_scope :user do
    authenticated :user do
    	root to: 'searchs#index'

      resources :searchs, only: %i[index]
      resources :mangas, only: %i[index show]
      resources :chapters, only: %i[show]
      post 'images/show', to: 'images#show_image', as: :show_image

      resources :mangamarks, only: %i[create destroy]
      resources :chapter_visiteds, only: %i[create destroy]

      get 'news', to: 'dashboards#news', as: :news
      get 'api', to: 'dashboards#api', as: :api

    	post 'search', to: 'searchs#search', as: :search
    end
    unauthenticated :user do
    	root to: 'devise/sessions#new'
    end
  end
end

app/models/manga.rb
class Manga < ApplicationRecord

	has_many :chapters, -> { order('position DESC') }, dependent: :destroy
	has_many :mangamarks, dependent: :destroy

	def json_for_api
		self.as_json(
			only: %i[id title cover],
			include: {
				chapters: {
					only: %i[id title position]
				}
			}
		)
	end

	# Description: Получить главы для текущей манги со статусами просмотра юзера
	# Params %i[user_id]
	def chapters_with_status(user_id)
		query = <<-SQL
			SELECT
				chapters.id AS id, 
				chapters.title AS title, 
				chapters.position AS position,
				CASE WHEN chapter_visiteds.id IS NULL THEN false ELSE true END AS status
			FROM chapters
			LEFT JOIN chapter_visiteds ON chapter_visiteds.chapter_id = chapters.id AND chapter_visiteds.user_id = '#{user_id}'
			WHERE chapters.manga_id = '#{self.id}'
			ORDER BY chapters.position DESC
		SQL
		ActiveRecord::Base.connection.exec_query(query).to_hash
	end

	# Description: Загрузить и сохранить главы для текущей манги
	# Params %i[]
	def loadChapters
		manga_host = URI(self.link).host.to_s

		hosts = JSON.parse(ENV['MANGA_HOST_URLS'])
		headers = JSON.parse(ENV['HEADERS'])

		response = HTTParty.get(self.link, {
    	headers: headers
    })

		html_doc = Nokogiri::HTML(response.body)

		chapter_results = html_doc.at_css('div.chapters-link table')

		_chapters = []

		(chapter_results&.children || []).each do |children|

			next if children.name != 'tr'

			children.children.each do |children_children|
				next if children_children.name != 'td'

				link_with_title = children_children.at_css('a')

				next if link_with_title.nil?

				_link = link_with_title['href']
				host = URI(_link).host.to_s

				next unless hosts.include?(host)

				_title = link_with_title.text.split(' ').join(' ')
				_title.slice!('новое')
				
				_link = "http://" + manga_host + _link if host.blank?

				_chapters.push(title: _title, link: _link)						
			end	
		end

		return if _chapters.blank?

		self.transaction do
			sql_query = <<-SQL
				INSERT INTO chapters (link, title, position, manga_id, created_at, updated_at)
					SELECT 
						elem ->> 'link',
						elem ->> 'title',
						pos,
						'#{self.id}',
						CURRENT_TIMESTAMP,
						CURRENT_TIMESTAMP 
					FROM jsonb_array_elements(?) WITH ORDINALITY arr(elem, pos)
				ON CONFLICT (manga_id, position) DO UPDATE
				SET updated_at = CURRENT_TIMESTAMP,
						title = EXCLUDED.title
			SQL
			ActiveRecord::Base.connection.execute(
				ActiveRecord::Base.send(
					:sanitize_sql_array, [
						sql_query,
						_chapters.reverse.to_json
					]
				)
			)
		end
	rescue StandardError => e
		Rails.logger.error e
		Rails.logger.error e.backtrace
	ensure
		return
	end
end

app/controllers/api/v1/mangas_controller.rb
class Api::V1::MangasController < ApiController

	# Method: GET
	# URL:
	# Description:
	# Params: %i[id]
	def show
		manga = Manga.find_by!(show_params)

		render json: manga.json_for_api, status: 200
	end

	private

		def show_params
			params.permit(:id)
		end

end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController

	include ApplicationHelper

	before_action :current_path

	# Method: GET
	# URL:
	# Description: получить закладки текущего пользователя
	# Params: %i[]
	def index
		datas = current_user.mangas.as_json
		
		@mangas = []
		promises = []

		datas.each do |data|
			promises << Concurrent::Promise.execute do
				{
					"cover_base64" => image_base64(data['cover'])
				}.merge!(data)
			end
		end

		@mangas = Concurrent::Promise.zip(*promises).value!
	end

	# Method: GET
	# URL:
	# Description: получить мангу по id
	# Params: %i[id]
	def show
		@manga = Manga.find(params[:id])

		@manga.loadChapters
		@manga.reload
		
		@chapters = @manga.chapters_with_status(current_user.id)
	end

	private

		def current_path
			@manga_path = true
		end
end

app/views/mangas/_chapter.html.erb
<tr class='row m-0'>
  <th class="col-2 col-sm-2 col-md-2 col-lg-1 col-xl-1 d-flex justify-content-center"><%= chapter['position'] %></th>
  <th class="col-8 col-sm-8 col-md-8 col-lg-10 col-xl-10">
  	<%= link_to(chapter['title'], chapter_path(chapter['id'])) %>
  </th>
  <th class="col-2 col-sm-2 col-md-2 col-lg-1 col-xl-1 d-flex justify-content-center">
  	<% if chapter['status'] %>
  		<%= fa_icon "eye", class: 'eye__show' %>
  	<% else %>
  		<%= fa_icon "eye-slash", class: 'eye__not-show' %>
  	<% end %>
  </th>
</tr>

app/views/mangas/index.html.erb
<%= render :partial => 'layouts/navigation' %>

<div class="row-fluid manga__list pt-5" id="mangas">
	<%= render :partial => 'layouts/manga_show', :collection => @mangas, :as => :manga %>
</div>

<div class="row-fluid pt-5 d-flex justify-content-center">
	<%#= will_paginate @mangas%>
</div>

app/views/mangas/show.html.erb
<%= render :partial => 'layouts/navigation' %>

<div class="row p-2 m-0 d-flex justify-content-center align-items-center">
  <%= link_to(mangas_path, class: 'btn btn-info mr-2') do %>
    <%= fa_icon "long-arrow-left" %>
  <% end %>
  <h4 class="m-0"><%= @manga.title %></h4>
</div>

<div class="row-fluid pb-5" id="manga">
	<div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 table-responsive">
		<table class="table table-hover table-sm">
			<thead>
        <tr class='row m-0'>
          <th class="col-2 col-sm-2 col-md-2 col-lg-1 col-xl-1 d-flex justify-content-center">#</th>
          <th class="col-8 col-sm-8 col-md-8 col-lg-10 col-xl-10">Название</th>
          <th class="col-2 col-sm-2 col-md-2 col-lg-1 col-xl-1 d-flex justify-content-center">Статус</th>
        </tr>
      </thead>
      <tbody>
      	<%= render :partial => 'mangas/chapter', :collection => @chapters, :as => :chapter %>
      </tbody>
		</table>
	</div>
</div>