config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[show]
      post 'users/sign_in', to: 'users#sign_in'

      resources :mangas, only: %i[show]
      resources :chapters, only: %i[show]
    end
  end

  devise_scope :user do
    authenticated :user do
    	root to: 'searchs#index'

      resources :searchs, only: %i[index]
      resources :mangas, only: %i[index show]
      resources :chapters, only: %i[show]
      post 'images/show', to: 'images#show_image', as: :show_image

      resources :mangamarks, only: %i[create destroy]
      resources :chapter_visiteds, only: %i[create destroy]

      get 'news', to: 'dashboards#news', as: :news
      get 'api', to: 'dashboards#api', as: :api

    	post 'search', to: 'searchs#search', as: :search
    end
    unauthenticated :user do
    	root to: 'devise/sessions#new'
    end
  end
end

app/models/chapter.rb
class Chapter < ApplicationRecord

	require 'httparty'

	belongs_to :manga

	has_many :images, -> { order('position ASC') }, dependent: :destroy
	has_many :chapter_visiteds, dependent: :destroy

	def next_id
		res = ActiveRecord::Base.connection.exec_query("
			SELECT
				id
			FROM chapters
			WHERE manga_id = '#{self.manga_id}' 
				AND position = '#{self.position + 1}'
		").to_hash[0]

		return res ? res['id'] : nil
	end

	def prev_id
		res = ActiveRecord::Base.connection.exec_query("
			SELECT
				id
			FROM chapters
			WHERE manga_id = '#{self.manga_id}' 
				AND position = '#{self.position - 1}'
		").to_hash[0]

		return res ? res['id'] : nil
	end

	def json_for_api
		self.as_json(
			only: %i[id title position manga_id],
			include: {
				images: {
					only: %i[link position]
				}
			}
		)
	end

	# Description: Создает запись о просмотре юзером главы
	# Params: %i[user_id]
	def updateVisiteds(user_id)
		sql_query = <<-SQL
			INSERT INTO chapter_visiteds (chapter_id, user_id, created_at, updated_at)
			VALUES ('#{self.id}', '#{user_id}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
			ON CONFLICT (chapter_id, user_id) DO UPDATE
			SET updated_at = CURRENT_TIMESTAMP
		SQL
		ActiveRecord::Base.connection.exec_query(sql_query)
	end

	# Description: Загрузить и сохранить слайды для текущей главы
	# Params %i[]
	def loadImages
		headers = JSON.parse(ENV['HEADERS'])

		response = HTTParty.get(self.link + "?mtr=1", {
    	headers: headers
    })

    _images = []

    text_with_images_links = /rm_h.init\((.+)\)/.match(response.body)[0]
    text_with_images_links = /\[(.+)\]/.match(text_with_images_links)[0]
    array_with_images_links = eval(text_with_images_links)

	  array_with_images_links.each_with_index do |image_link|
	  	next if image_link.nil?

	    _link = image_link[1] + image_link[2]
	    _images.push(link: _link)
		end
		
		return if _images.blank?

	  self.transaction do
	  	sql_query = <<-SQL
				INSERT INTO images (position, link, chapter_id, created_at, updated_at)
					SELECT 
						pos,
						elem ->> 'link',
						'#{self.id}',
						CURRENT_TIMESTAMP,
						CURRENT_TIMESTAMP 
					FROM jsonb_array_elements(?) WITH ORDINALITY arr(elem, pos)
				ON CONFLICT (chapter_id, position) DO UPDATE
				SET updated_at = CURRENT_TIMESTAMP
			SQL
			ActiveRecord::Base.connection.execute(
				ActiveRecord::Base.send(
					:sanitize_sql_array, [
						sql_query,
						_images.to_json
					]
				)
			)
	  end
	rescue StandardError => e
		Rails.logger.error e
		Rails.logger.error e.backtrace
	ensure
		return
	end

end

app/controllers/api/v1/chapters_controller.rb
class Api::V1::ChaptersController < ApiController

	# Method: GET
	# URL:
	# Description:
	# Params: %i[id]
	def show
		chapter = Chapter.find_by!(show_params)

		render json: chapter.json_for_api, status: 200
	end

	private

		def show_params
			params.permit(:id)
		end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

	before_action :current_path

	# Method: GET
	# URL:
	# Description: получить главу манги. Загрузить изображения, если нету. Создать запись в просмотренных
	# Params: %i[id]
	def show
		@chapter = Chapter.find(params[:id])

		@chapter.updateVisiteds(current_user.id)

		if @chapter.images.blank?
			@chapter.loadImages
			@chapter.reload
		end
	end

	private

		def current_path
			@manga_path = true
		end
end

app/views/chapters/show.html.erb
<%= render :partial => 'layouts/navigation' %>

<div class="row p-2 m-0 d-flex justify-content-center align-items-center">
	<%= link_to(manga_path(@chapter.manga_id), class: 'btn btn-warning mr-2') do %>
		List
	<% end %>
</div>

<div class="row p-2 m-0 d-flex justify-content-center align-items-center">
	<% if @chapter.prev_id %>
		<%= link_to(chapter_path(@chapter.prev_id), class: 'btn btn-info mr-2') do %>
			<%= fa_icon "long-arrow-left" %>
		<% end %>
	<% end %>

	<h4 class="m-0"><%= @chapter.title %></h4>

	<% if @chapter.next_id %>
		<%= link_to(chapter_path(@chapter.next_id), class: 'btn btn-info ml-2') do %>
			<%= fa_icon "long-arrow-right" %>
		<% end %>
	<% end %>
</div>

<div class="row p-2 m-0">
	<div class="col-sm-4 d-flex justify-content-center"><button class="btn btn-primary" id="slidesPrev">Prev</button></div>
	<div class="col-sm-4 d-flex justify-content-center"><span id="slidesPosition"></span></div>
	<div class="col-sm-4 d-flex justify-content-center"><button class="btn btn-primary" id="slidesNext">Next</button></div>
</div>

<div class="row-fluid h-100 pb-5">
	<div id="chapter__images">
		<div class="chapter__image d-flex justify-content-center" id="currentSlide">
		</div>
  </div>
</div>

<script type="text/javascript">
	$(function() {
		const images = <%= @chapter.images.pluck(:id).to_json.html_safe %>;

		let current_slide = 1

		function render(position) {
			new Promise(function(resolve, reject) {
				$("#currentSlide").html("<%= j render :partial => 'layouts/preloader' %>")
				$.post("<%= show_image_path %>", { id: images[current_slide - 1] })
				$('#slidesPosition').text(`${current_slide}/${images.length}`)
			})
		}

		render(current_slide)

		$('#slidesPrev').on('click', function() {
			if (current_slide > 1) {
				current_slide -= 1
				render(current_slide)
			}
		})

		$('#slidesNext').on('click', function() {
			if (current_slide < images.length) {
				current_slide += 1
				render(current_slide)
			}
		})

	})
</script>