config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[show]
      post 'users/sign_in', to: 'users#sign_in'

      resources :mangas, only: %i[show]
      resources :chapters, only: %i[show]
    end
  end

  devise_scope :user do
    authenticated :user do
    	root to: 'searchs#index'

      resources :searchs, only: %i[index]
      resources :mangas, only: %i[index show]
      resources :chapters, only: %i[show]
      post 'images/show', to: 'images#show_image', as: :show_image

      resources :mangamarks, only: %i[create destroy]
      resources :chapter_visiteds, only: %i[create destroy]

      get 'news', to: 'dashboards#news', as: :news
      get 'api', to: 'dashboards#api', as: :api

    	post 'search', to: 'searchs#search', as: :search
    end
    unauthenticated :user do
    	root to: 'devise/sessions#new'
    end
  end
end

app/views/layouts/_manga_search.html.erb
<div class="manga__item" id="<%= manga[:index] %>">
	<div class="manga__cover"><%= image_tag(manga[:cover_base64], alt: manga[:title], title: manga[:title]) %></div>
	<div class="manga__title"><%= manga[:title] %></div>
	<div class="manga_buttons">
		<%= button_to(mangamarks_path, method: :post, remote: true, params: { manga: manga.slice(:title, :cover, :link) }, class: 'manga__button add btn btn-dark') do %>
			Добавить
		<% end %>
	</div>
</div>

app/views/layouts/_manga_show.html.erb
<div class="manga__item" id="<%= manga['id'] %>">
	<div class="manga__cover"><%= image_tag(manga['cover_base64'], alt: manga['title'], title: manga['title']) %></div>
	<div class="manga__title"><%= manga['title'] %></div>
	<div class="manga_buttons">
		<%= link_to('Читать', manga_path(manga['id']), class: 'manga__button show btn btn-dark') %>
		<%= link_to(mangamark_path(manga['id']), class: 'manga__button destroy btn btn-danger', method: :delete, remote: true) do %><%= fa_icon "trash" %><% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<div class="row-fluid" id="navigations">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">MangaReader</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if @search_path %>">
          <%= link_to 'Поиск', searchs_path, class: 'nav-link'%>
        </li>
        <li class="nav-item <%= 'active' if @manga_path %>">
          <%= link_to 'Закладки', mangas_path, class: 'nav-link'%>
        </li>
        <li class="nav-item <%= 'active' if @api_path %>">
          <%= link_to 'API', api_path, class: 'nav-link'%>
        </li>
      </ul>
      <%= link_to(destroy_user_session_path, class: 'leave', method: :delete) do %>
        <%= fa_icon "sign-out" %>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/_preloader.html.erb
<div class="sk-circle">
	<div class="sk-circle1 sk-child"></div>
	<div class="sk-circle2 sk-child"></div>
	<div class="sk-circle3 sk-child"></div>
	<div class="sk-circle4 sk-child"></div>
	<div class="sk-circle5 sk-child"></div>
	<div class="sk-circle6 sk-child"></div>
	<div class="sk-circle7 sk-child"></div>
	<div class="sk-circle8 sk-child"></div>
	<div class="sk-circle9 sk-child"></div>
	<div class="sk-circle10 sk-child"></div>
	<div class="sk-circle11 sk-child"></div>
	<div class="sk-circle12 sk-child"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MdProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid p-0">
    <div class="row-fluid">
      <%= yield %>
    </div>
  </body>
</html>